import "~/styles/globals.css";

import { type Metadata } from "next";
import { Lobster, Outfit } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { SessionProvider } from "next-auth/react";
import { auth } from "~/server/auth";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit-sans",
});

const lobser = Lobster({
  subsets: ["latin"],
  variable: "--font-lobster",
  weight: "400",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  return (
    <html lang="en" className={`${outfit.variable} ${lobser.variable}`}>
      <body>
        <SessionProvider session={session}>
          <TRPCReactProvider>
            <div className="from-primary-300 to-primary-500 grainy relative z-0 flex min-h-screen flex-col items-center text-white">
              {children}
              <Image
                priority
                src="/texture.jpg"
                alt="Texture"
                fill
                className="absolute inset-0 -z-10 object-cover opacity-10 mix-blend-multiply"
              />
            </div>
          </TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
